package com.company;

import java.sql.Array;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

public class SpeedTest {

    private static final Pitanje[] democracyQuestions = {
            new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""),
            new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""),
            new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""),
            new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""),
            new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""),
            new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""),
            new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""),
            new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""),
            new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""),
            new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"),
            new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""),
            new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""),
            new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""),
            new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""),
            new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""),
            new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""),
            new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""),
            new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""),
            new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""),
            new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""),
            new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""),
            new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"),
            new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""),
            new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""),
            new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""),
            new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""),
            new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""),
            new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""),
            new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""),
            new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""),
            new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""),
            new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""),
            new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""),
            new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"),
            new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""),
            new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""),
            new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""),
            new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""),
            new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""),
            new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""),
            new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""),
            new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""),
            new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""),
            new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""),
            new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""),
            new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"),
            new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""),
            new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""),
            new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""),
            new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""),
            new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""),
            new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""),
            new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""),
            new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""),
            new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""),
            new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""),
            new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""),
            new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"),
            new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""),
            new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""),
            new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""),
            new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""),
            new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""),
            new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""),
            new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""),
            new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""),
            new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""),
            new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""),
            new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""),
            new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"),
            new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""),
            new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10","")
    };



    public static int[] randomNumberGenerator(int start, int end, int count) {
        Random rng = new Random();

        int[] result = new int[count];
        int cur = 0;
        int remaining = end - start;
        for (int i = start; i < end && count > 0; i++) {
            double probability = rng.nextDouble();
            if (probability < ((double) count) / (double) remaining) {
                count--;
                result[cur++] = i;
            }
            remaining--;
        }
        return result;
    }


    public static ArrayList<Pitanje> getDemocracy(){
        long startTime = System.nanoTime();
        ArrayList<Pitanje> Democracy = new ArrayList<>();
        Democracy.add(new Pitanje("Pravednost načina na koji se prikupljaju informacije u donošenju odluka definira","proceduralnu pravdu","distributivnu pravdu","korektivnu pravdu","administrativnu pravdu",""));
        Democracy.add(new Pitanje("Koja grana vlasti donosi zakone u državi:","zakonodavna","sudska (pravosudna)","izvršna","lokalna",""));
        Democracy.add(new Pitanje("Na kojem nivou vlasti se vodi vanjska politika BiH?","državnom","entitetskom","lokalnom","na nivou mjesne zajednice","Vanjsku politiku Bosne i Hercegovine vodi tročlano Predsjedništvo i Ministarstvo vanjskih poslova"));
        Democracy.add(new Pitanje("Predsjedništvo BiH vrši sljedeću vlast?","izvršnu","zakonodavnu","sudsku","lokalnu",""));
        Democracy.add(new Pitanje("Magna Karta (Velika povelja) nastala je","1215.","1212.","1216.","1463.","Magna Carta je predstavljala prvi pisani ustavni dokument u engleskoj historiji i presedan kojim je ustanovljen princip ljudskih i građanskih prava u anglosaksonskoj pravnoj tradiciji."));
        Democracy.add(new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""));
        Democracy.add(new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""));
        Democracy.add(new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""));
        Democracy.add(new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""));
        Democracy.add(new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""));
        Democracy.add(new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""));
        Democracy.add(new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""));
        Democracy.add(new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""));
        Democracy.add(new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""));
        Democracy.add(new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"));
        Democracy.add(new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""));
        Democracy.add(new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""));
        Democracy.add(new Pitanje("Pravednost načina na koji se prikupljaju informacije u donošenju odluka definira","proceduralnu pravdu","distributivnu pravdu","korektivnu pravdu","administrativnu pravdu",""));
        Democracy.add(new Pitanje("Koja grana vlasti donosi zakone u državi:","zakonodavna","sudska (pravosudna)","izvršna","lokalna",""));
        Democracy.add(new Pitanje("Na kojem nivou vlasti se vodi vanjska politika BiH?","državnom","entitetskom","lokalnom","na nivou mjesne zajednice","Vanjsku politiku Bosne i Hercegovine vodi tročlano Predsjedništvo i Ministarstvo vanjskih poslova"));
        Democracy.add(new Pitanje("Predsjedništvo BiH vrši sljedeću vlast?","izvršnu","zakonodavnu","sudsku","lokalnu",""));
        Democracy.add(new Pitanje("Magna Karta (Velika povelja) nastala je","1215.","1212.","1216.","1463.","Magna Carta je predstavljala prvi pisani ustavni dokument u engleskoj historiji i presedan kojim je ustanovljen princip ljudskih i građanskih prava u anglosaksonskoj pravnoj tradiciji."));
        Democracy.add(new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""));
        Democracy.add(new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""));
        Democracy.add(new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""));
        Democracy.add(new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""));
        Democracy.add(new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""));
        Democracy.add(new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""));
        Democracy.add(new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""));
        Democracy.add(new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""));
        Democracy.add(new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""));
        Democracy.add(new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"));
        Democracy.add(new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""));
        Democracy.add(new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""));
        Democracy.add(new Pitanje("Pravednost načina na koji se prikupljaju informacije u donošenju odluka definira","proceduralnu pravdu","distributivnu pravdu","korektivnu pravdu","administrativnu pravdu",""));
        Democracy.add(new Pitanje("Koja grana vlasti donosi zakone u državi:","zakonodavna","sudska (pravosudna)","izvršna","lokalna",""));
        Democracy.add(new Pitanje("Na kojem nivou vlasti se vodi vanjska politika BiH?","državnom","entitetskom","lokalnom","na nivou mjesne zajednice","Vanjsku politiku Bosne i Hercegovine vodi tročlano Predsjedništvo i Ministarstvo vanjskih poslova"));
        Democracy.add(new Pitanje("Predsjedništvo BiH vrši sljedeću vlast?","izvršnu","zakonodavnu","sudsku","lokalnu",""));
        Democracy.add(new Pitanje("Magna Karta (Velika povelja) nastala je","1215.","1212.","1216.","1463.","Magna Carta je predstavljala prvi pisani ustavni dokument u engleskoj historiji i presedan kojim je ustanovljen princip ljudskih i građanskih prava u anglosaksonskoj pravnoj tradiciji."));
        Democracy.add(new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""));
        Democracy.add(new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""));
        Democracy.add(new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""));
        Democracy.add(new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""));
        Democracy.add(new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""));
        Democracy.add(new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""));
        Democracy.add(new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""));
        Democracy.add(new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""));
        Democracy.add(new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""));
        Democracy.add(new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"));
        Democracy.add(new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""));
        Democracy.add(new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""));
        Democracy.add(new Pitanje("Pravednost načina na koji se prikupljaju informacije u donošenju odluka definira","proceduralnu pravdu","distributivnu pravdu","korektivnu pravdu","administrativnu pravdu",""));
        Democracy.add(new Pitanje("Koja grana vlasti donosi zakone u državi:","zakonodavna","sudska (pravosudna)","izvršna","lokalna",""));
        Democracy.add(new Pitanje("Na kojem nivou vlasti se vodi vanjska politika BiH?","državnom","entitetskom","lokalnom","na nivou mjesne zajednice","Vanjsku politiku Bosne i Hercegovine vodi tročlano Predsjedništvo i Ministarstvo vanjskih poslova"));
        Democracy.add(new Pitanje("Predsjedništvo BiH vrši sljedeću vlast?","izvršnu","zakonodavnu","sudsku","lokalnu",""));
        Democracy.add(new Pitanje("Magna Karta (Velika povelja) nastala je","1215.","1212.","1216.","1463.","Magna Carta je predstavljala prvi pisani ustavni dokument u engleskoj historiji i presedan kojim je ustanovljen princip ljudskih i građanskih prava u anglosaksonskoj pravnoj tradiciji."));
        Democracy.add(new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""));
        Democracy.add(new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""));
        Democracy.add(new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""));
        Democracy.add(new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""));
        Democracy.add(new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""));
        Democracy.add(new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""));
        Democracy.add(new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""));
        Democracy.add(new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""));
        Democracy.add(new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""));
        Democracy.add(new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"));
        Democracy.add(new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""));
        Democracy.add(new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""));
        Democracy.add(new Pitanje("Pravednost načina na koji se prikupljaju informacije u donošenju odluka definira","proceduralnu pravdu","distributivnu pravdu","korektivnu pravdu","administrativnu pravdu",""));
        Democracy.add(new Pitanje("Koja grana vlasti donosi zakone u državi:","zakonodavna","sudska (pravosudna)","izvršna","lokalna",""));
        Democracy.add(new Pitanje("Na kojem nivou vlasti se vodi vanjska politika BiH?","državnom","entitetskom","lokalnom","na nivou mjesne zajednice","Vanjsku politiku Bosne i Hercegovine vodi tročlano Predsjedništvo i Ministarstvo vanjskih poslova"));
        Democracy.add(new Pitanje("Predsjedništvo BiH vrši sljedeću vlast?","izvršnu","zakonodavnu","sudsku","lokalnu",""));
        Democracy.add(new Pitanje("Magna Karta (Velika povelja) nastala je","1215.","1212.","1216.","1463.","Magna Carta je predstavljala prvi pisani ustavni dokument u engleskoj historiji i presedan kojim je ustanovljen princip ljudskih i građanskih prava u anglosaksonskoj pravnoj tradiciji."));
        Democracy.add(new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""));
        Democracy.add(new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""));
        Democracy.add(new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""));
        Democracy.add(new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""));
        Democracy.add(new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""));
        Democracy.add(new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""));
        Democracy.add(new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""));
        Democracy.add(new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""));
        Democracy.add(new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""));
        Democracy.add(new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"));
        Democracy.add(new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""));
        Democracy.add(new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""));
        Democracy.add(new Pitanje("Pravednost načina na koji se prikupljaju informacije u donošenju odluka definira","proceduralnu pravdu","distributivnu pravdu","korektivnu pravdu","administrativnu pravdu",""));
        Democracy.add(new Pitanje("Koja grana vlasti donosi zakone u državi:","zakonodavna","sudska (pravosudna)","izvršna","lokalna",""));
        Democracy.add(new Pitanje("Na kojem nivou vlasti se vodi vanjska politika BiH?","državnom","entitetskom","lokalnom","na nivou mjesne zajednice","Vanjsku politiku Bosne i Hercegovine vodi tročlano Predsjedništvo i Ministarstvo vanjskih poslova"));
        Democracy.add(new Pitanje("Predsjedništvo BiH vrši sljedeću vlast?","izvršnu","zakonodavnu","sudsku","lokalnu",""));
        Democracy.add(new Pitanje("Magna Karta (Velika povelja) nastala je","1215.","1212.","1216.","1463.","Magna Carta je predstavljala prvi pisani ustavni dokument u engleskoj historiji i presedan kojim je ustanovljen princip ljudskih i građanskih prava u anglosaksonskoj pravnoj tradiciji."));
        Democracy.add(new Pitanje("Biračko pravo (Pravo da bira i bude biran) spada u grupu","Političkih prava","građanskih prava","ekonomskih prava","kulturnih prava",""));
        Democracy.add(new Pitanje("Ograničena vlast je","Vladavina uspostavljena ograničenjem svojih moći putem zakona i slobodnih izbora koje  poštuju","Vladavina uspostavljena od strane manjeg broja ljudi koji sami donose zakone","Vladavina uspostavljena vladavinom bogatih ljudi koji o svemu odlučuju","Vladavina uspostavljena voljom pojedinca ili grupe i za vladavinu im nisu potrebni zakoni",""));
        Democracy.add(new Pitanje("Referendum je","Oblik neposrednog odlučivanja, izjašnjavanje građana o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posrednog odlučivanja u parlamentu o nekim naročito važnim pitanjima. Izjašnjava   se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik posebnog odlučivanja u sudovima u kojima se utvrđuje krivnja o nekim naročito važnim pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“","Oblik glasanja u parlamentu u kojem se parlamentarci izjašnjavaju o nekim naročito važnim     pitanjima. Izjašnjava se samo sa „da“ ili „ne“ ili „za“ ili „protiv“",""));
        Democracy.add(new Pitanje("Ustav je","obično dokument ili skup dokumenata koji određuje osnovne zakone i principe ili uređenje vlasti političkog sistema","usmeni dogovor predstavnika svih nivoa vlasti","završna odredba mirovnih sporazuma u kojima je glavnu ulogu preuzela Generalna skupština UN","normativ kojim se usklađuju odnosi između stranaka na vlasti i stranaka u opoziciji",""));
        Democracy.add(new Pitanje("Brčko je","distrikt","kanton","Općina","entitet",""));
        Democracy.add(new Pitanje("Koja su prirodna prava čovjeka","pravo na život, imovinu i slobodu","pravo na obrazovanje, slobodu izražavanja i zdravu hranu","pravo na slobodu kretanja, prebivališta i zdravu životnu sredinu","pravo na slobodu misli, savjesti i vjere",""));
        Democracy.add(new Pitanje("Opozicija je","manjinska politička partija koja nije na vlasti","stranka na vlasti","politička partija koja se takmiči za vlast","stranka koja nije parlamentarna",""));
        Democracy.add(new Pitanje("Interesne grupe su","Postdejtonske formalno organizirane skupine ljudi koje vrše utjecaj na vršenje zakonodavne, izvršne i sudske vlasti sa ciljem očuvanja ustavnog ustrojstva države, njenog suvereniteta i teritorijalnog integriteta","Formalne i neformalne skupine organizirane oko ostvarivanja zajedničkih ciljeva u očuvanju životne sredine i zaštiti socijalne sigurnosti građana","Udruženja građana sastavljena od pojedinaca ili organizacija koje se okupljaju da unaprijede neka dobra ili beneficije za svoje članove ili za javnost općenito putem utjecaja na politiku vlasti","Slobodno udruživanje građana u državi sa ciljem osnivanja političkih stranaka i uspostavom demokratskog sistema vladavine u oblasti ekonomije i privrede",""));
        Democracy.add(new Pitanje("Jedna od navedenih osobina predstavlja karakteristiku nedemokratskoh sistema:","Moć nije podijeljena","Sloboda kretanja","Vladavina prava","Pravedan zakonski proces",""));
        Democracy.add(new Pitanje("Monetarna politika spada u nadležnost","države","kantona","entiteta","Brčko Distrikta","Monetarna politika Bosne i Hercegovine regulirana je Zakonom o Centralnoj banci Bosne i Hercegovine"));
        Democracy.add(new Pitanje("Koja je primarna funkcija vlasti u demokratskom društvu?","da štiti prava i slobode svojih građana","da štiti i upravlja slobodama građana","da krši prava i slobode svojih građana","da rukovodi njihovim pravima i slobodama",""));
        Democracy.add(new Pitanje("Koliko članova broji Predsjedništvo BiH?","3","4","8","10",""));

        Collections.shuffle(Democracy);

        long endTime = System.nanoTime();
        long timeElapsed = endTime - startTime;
        System.out.println("Execution time in nanoseconds  : " + timeElapsed);

        return Democracy;
    }


    public static Pitanje[]  getPrimitiveDemocracy(int numberOfQuestions) {
        Pitanje[] questions = new Pitanje[numberOfQuestions];
        int[] indexes = randomNumberGenerator(0,democracyQuestions.length, numberOfQuestions);
        for (int i=0;i<numberOfQuestions;i++){
            questions[i] = democracyQuestions[indexes[i]];
        }

        return questions;
    }


    public static void main(String[] args) {
        ArrayList<Pitanje> oldDemocracy = getDemocracy();
        long startTime = System.nanoTime();
        Pitanje[] newDemocracy = getPrimitiveDemocracy(5);
        long endTime = System.nanoTime();
        long timeElapsed = endTime - startTime;
        System.out.println("Execution time in nanoseconds  : " + timeElapsed);

        for (Pitanje pitanje: newDemocracy) {
            System.out.println(pitanje.getQuestion());
        }
    }


}
